# ============================================================
# graph/research_graph.py
# ============================================================
# PURPOSE:
#   This module is the CENTRAL ORCHESTRATOR of the entire multi-agent
#   research pipeline. It uses LangGraph to define a state machine
#   (a directed graph) that connects all 5 agents in sequence and
#   manages the flow of data between them.
#
# WHY WE NEED A GRAPH ORCHESTRATOR:
#   Without an orchestrator, we'd have to manually call each agent
#   and pass data between them in a long, fragile script. LangGraph
#   provides a structured, visual way to define agent pipelines:
#   - Each agent is a "node" in the graph
#   - Data flows between nodes through "edges"
#   - The "state" object carries all data through the pipeline
#   - The graph handles execution order automatically
#
#   This is the industry-standard pattern for building multi-agent
#   systems in 2024-2025. LangGraph is used by companies like
#   LinkedIn, Uber, and many AI startups for production agent systems.
#
# HOW LANGGRAPH WORKS (simplified):
#   1. Define a State class (TypedDict) -- this is the shared memory
#      that all agents read from and write to
#   2. Define node functions -- each agent is wrapped in a node function
#      that reads from state and returns updates to state
#   3. Build the graph -- connect nodes with edges (START -> node1 -> node2 -> END)
#   4. Compile the graph -- LangGraph validates the structure
#   5. Run the graph -- call graph.invoke(initial_state) to execute
#
# PIPELINE FLOW:
#   START
#     |
#   [planner_node]    -> Generates sub-questions from topic
#     |
#   [search_node]     -> Fetches web + Wikipedia results
#     |
#   [summarizer_node] -> Summarizes raw results per sub-topic
#     |
#   [writer_node]     -> Writes the full research report
#     |
#   [critic_node]     -> Evaluates and scores the report
#     |
#   [save_node]       -> Saves report to disk (if enabled)
#     |
#   END
#
# TECHNOLOGY USED:
#   - LangGraph: Agent orchestration framework by LangChain
#   - TypedDict: Python type system for defining the state schema
#   - All 5 agent modules from the agents/ directory
#   - config_loader: Reads settings from config.yaml
# ============================================================

from langgraph.graph import StateGraph, START, END          # LangGraph core components
from typing import TypedDict, List, Dict, Any, Optional     # Type hints for state definition
from utils.config_loader import load_config                  # Load settings from config.yaml

# Import all 5 agent runner functions
from agents.planner_agent import run_planner_agent           # Agent 1: Question decomposition
from agents.search_agent import run_search_agent             # Agent 2: Web + Wikipedia search
from agents.summarizer_agent import run_summarizer_agent     # Agent 3: Summarization
from agents.writer_agent import run_writer_agent             # Agent 4: Report writing
from agents.critic_agent import run_critic_agent             # Agent 5: Quality evaluation

import os           # For file path operations (saving reports)
import datetime     # For timestamped filenames


# ============================================================
# STATE DEFINITION
# ============================================================
# The ResearchState is the "shared memory" of the pipeline.
# Every agent reads from this state and writes updates back to it.
# LangGraph passes this state object between all nodes automatically.
#
# WHY TypedDict:
#   TypedDict gives us type safety -- we know exactly what fields
#   exist in the state and what types they should be. This prevents
#   bugs where an agent tries to read a field that doesn't exist.
#
# FIELD DESCRIPTIONS:
#   topic:          The user's research topic (set at the start, never changes)
#   config:         The loaded configuration dictionary (shared across all agents)
#   sub_questions:  Generated by Planner Agent, used by Search Agent
#   search_results: Generated by Search Agent, used by Summarizer Agent
#   summaries:      Generated by Summarizer Agent, used by Writer Agent
#   report:         Generated by Writer Agent, used by Critic Agent
#   review:         Generated by Critic Agent, final output
#   error:          Any error message (None if pipeline succeeded)
#   status:         Current pipeline status for UI progress tracking
# ============================================================

class ResearchState(TypedDict):
    """
    The shared state object that flows through the entire research pipeline.

    WHY THIS CLASS EXISTS:
        In LangGraph, all agents communicate through a shared state object.
        This TypedDict defines the exact schema of that state -- what data
        exists, what type it is, and what it means. Every agent reads
        from this state and returns a dictionary of updates to merge back in.

    FIELDS:
        topic (str):
            The original research topic entered by the user.
            Set once at the beginning, never modified.
            Example: "Impact of AI on Healthcare"

        config (dict):
            The loaded configuration from config.yaml.
            Shared across all agents to avoid reloading the file multiple times.
            Contains API keys, model settings, agent configs, etc.

        sub_questions (List[str]):
            Generated by the Planner Agent.
            A list of focused sub-questions derived from the topic.
            Example: ["What is AI in healthcare?", "What are AI diagnostic tools?", ...]

        search_results (Dict[str, Any]):
            Generated by the Search Agent.
            Maps each sub-question to its web + Wikipedia search results.
            Structure: {question: {web_results: [...], wikipedia: {...}, formatted_context: "..."}}

        summaries (Dict[str, str]):
            Generated by the Summarizer Agent.
            Maps each sub-question to a clean, concise summary.
            Structure: {question: "Summary text..."}

        report (str):
            Generated by the Writer Agent.
            The full research report in Markdown format.

        review (Dict[str, Any]):
            Generated by the Critic Agent.
            Contains score, grade, verdict, strengths, weaknesses, suggestions.

        error (Optional[str]):
            Set if any agent encounters a fatal error.
            None if the pipeline completed successfully.

        status (str):
            Current status message for UI progress tracking.
            Updated by each agent as it starts/completes.
    """
    topic: str
    config: dict
    sub_questions: List[str]
    search_results: Dict[str, Any]
    summaries: Dict[str, str]
    report: str
    review: Dict[str, Any]
    error: Optional[str]
    status: str


# ============================================================
# NODE FUNCTIONS
# ============================================================
# Each node function:
# 1. Receives the current state as input
# 2. Runs its agent
# 3. Returns a dictionary of state updates (only the fields it changes)
# LangGraph merges these updates into the state automatically.
# ============================================================

def planner_node(state: ResearchState) -> dict:
    """
    LangGraph node that runs the Planner Agent.

    WHY THIS FUNCTION EXISTS:
        LangGraph requires each agent to be wrapped in a "node function"
        that follows a specific signature: takes state as input, returns
        a dict of state updates. This wrapper function bridges the gap
        between LangGraph's interface and our Planner Agent's interface.

    HOW IT WORKS:
        1. Reads the topic and config from the current state
        2. Calls run_planner_agent() to generate sub-questions
        3. Returns a dict updating 'sub_questions' and 'status' in the state
        4. If an error occurs, sets the 'error' field in the state

    WHAT IT UPDATES IN STATE:
        - sub_questions: The list of generated sub-questions
        - status: Progress message for the UI

    Args:
        state (ResearchState): The current pipeline state.

    Returns:
        dict: State updates to merge into the pipeline state.
              Keys: 'sub_questions', 'status' (and 'error' if failed)
    """
    print("\n" + "="*60)
    print("AGENT 1/5: PLANNER AGENT")
    print("="*60)

    try:
        # Extract needed data from state
        topic = state["topic"]
        config = state["config"]

        # Run the Planner Agent
        sub_questions = run_planner_agent(topic=topic, config=config)

        return {
            "sub_questions": sub_questions,
            "status": f"Planner: Generated {len(sub_questions)} sub-questions"
        }

    except Exception as e:
        error_msg = f"Planner Agent failed: {str(e)}"
        print(f"ERROR: {error_msg}")
        return {
            "sub_questions": [state["topic"]],  # Fallback: use topic as single question
            "error": error_msg,
            "status": "Planner failed -- using fallback"
        }


def search_node(state: ResearchState) -> dict:
    """
    LangGraph node that runs the Search Agent.

    WHY THIS FUNCTION EXISTS:
        Wraps the Search Agent in LangGraph's node interface.
        Reads sub_questions from state (set by Planner Agent),
        runs web + Wikipedia searches, and updates search_results in state.

    HOW IT WORKS:
        1. Reads sub_questions and config from state
        2. Calls run_search_agent() to fetch web + Wikipedia results
        3. Returns a dict updating 'search_results' and 'status'

    WHAT IT UPDATES IN STATE:
        - search_results: Dict mapping questions to their search results
        - status: Progress message for the UI

    Args:
        state (ResearchState): The current pipeline state.

    Returns:
        dict: State updates with 'search_results' and 'status'.
    """
    print("\n" + "="*60)
    print("AGENT 2/5: SEARCH AGENT")
    print("="*60)

    try:
        sub_questions = state["sub_questions"]
        config = state["config"]

        # Run the Search Agent
        search_results = run_search_agent(
            sub_questions=sub_questions,
            config=config
        )

        total_web = sum(len(r.get("web_results", [])) for r in search_results.values())

        return {
            "search_results": search_results,
            "status": f"Search: Found {total_web} web results for {len(search_results)} questions"
        }

    except Exception as e:
        error_msg = f"Search Agent failed: {str(e)}"
        print(f"ERROR: {error_msg}")
        return {
            "search_results": {},
            "error": error_msg,
            "status": "Search failed"
        }


def summarizer_node(state: ResearchState) -> dict:
    """
    LangGraph node that runs the Summarizer Agent.

    WHY THIS FUNCTION EXISTS:
        Wraps the Summarizer Agent in LangGraph's node interface.
        Reads search_results from state (set by Search Agent),
        generates clean summaries, and updates summaries in state.

    HOW IT WORKS:
        1. Reads search_results and config from state
        2. Calls run_summarizer_agent() to generate summaries
        3. Returns a dict updating 'summaries' and 'status'

    WHAT IT UPDATES IN STATE:
        - summaries: Dict mapping questions to their summaries
        - status: Progress message for the UI

    Args:
        state (ResearchState): The current pipeline state.

    Returns:
        dict: State updates with 'summaries' and 'status'.
    """
    print("\n" + "="*60)
    print("AGENT 3/5: SUMMARIZER AGENT")
    print("="*60)

    try:
        search_results = state["search_results"]
        config = state["config"]

        # Run the Summarizer Agent
        summaries = run_summarizer_agent(
            search_results=search_results,
            config=config
        )

        return {
            "summaries": summaries,
            "status": f"Summarizer: Created {len(summaries)} topic summaries"
        }

    except Exception as e:
        error_msg = f"Summarizer Agent failed: {str(e)}"
        print(f"ERROR: {error_msg}")
        return {
            "summaries": {},
            "error": error_msg,
            "status": "Summarizer failed"
        }


def writer_node(state: ResearchState) -> dict:
    """
    LangGraph node that runs the Writer Agent.

    WHY THIS FUNCTION EXISTS:
        Wraps the Writer Agent in LangGraph's node interface.
        Reads topic and summaries from state, writes the full report,
        and updates the report field in state.

    HOW IT WORKS:
        1. Reads topic, summaries, and config from state
        2. Calls run_writer_agent() to generate the full report
        3. Returns a dict updating 'report' and 'status'

    WHAT IT UPDATES IN STATE:
        - report: The complete Markdown research report
        - status: Progress message for the UI

    Args:
        state (ResearchState): The current pipeline state.

    Returns:
        dict: State updates with 'report' and 'status'.
    """
    print("\n" + "="*60)
    print("AGENT 4/5: WRITER AGENT")
    print("="*60)

    try:
        topic = state["topic"]
        summaries = state["summaries"]
        config = state["config"]

        # Run the Writer Agent
        report = run_writer_agent(
            topic=topic,
            summaries=summaries,
            config=config
        )

        word_count = len(report.split())

        return {
            "report": report,
            "status": f"Writer: Report generated ({word_count} words)"
        }

    except Exception as e:
        error_msg = f"Writer Agent failed: {str(e)}"
        print(f"ERROR: {error_msg}")
        return {
            "report": f"# Report Generation Failed\n\nError: {str(e)}",
            "error": error_msg,
            "status": "Writer failed"
        }


def critic_node(state: ResearchState) -> dict:
    """
    LangGraph node that runs the Critic Agent.

    WHY THIS FUNCTION EXISTS:
        Wraps the Critic Agent in LangGraph's node interface.
        Reads topic and report from state, evaluates the report quality,
        and updates the review field in state.

    HOW IT WORKS:
        1. Reads topic, report, and config from state
        2. Calls run_critic_agent() to evaluate the report
        3. Returns a dict updating 'review' and 'status'

    WHAT IT UPDATES IN STATE:
        - review: Dict with score, grade, verdict, strengths, weaknesses, suggestions
        - status: Progress message for the UI

    Args:
        state (ResearchState): The current pipeline state.

    Returns:
        dict: State updates with 'review' and 'status'.
    """
    print("\n" + "="*60)
    print("AGENT 5/5: CRITIC AGENT")
    print("="*60)

    try:
        topic = state["topic"]
        report = state["report"]
        config = state["config"]

        # Run the Critic Agent
        review = run_critic_agent(
            topic=topic,
            report=report,
            config=config
        )

        score = review.get("score", "N/A")
        verdict = review.get("verdict", "Unknown")

        return {
            "review": review,
            "status": f"Critic: Score {score}/10 | {verdict}"
        }

    except Exception as e:
        error_msg = f"Critic Agent failed: {str(e)}"
        print(f"ERROR: {error_msg}")
        return {
            "review": {
                "score": 0,
                "grade": "N/A",
                "verdict": "EVALUATION FAILED",
                "full_review": f"Critic evaluation failed: {str(e)}"
            },
            "error": error_msg,
            "status": "Critic failed"
        }


def save_node(state: ResearchState) -> dict:
    """
    LangGraph node that saves the final report and review to disk.

    WHY THIS FUNCTION EXISTS:
        After the pipeline completes, users want to save their research
        reports for future reference. This node handles saving the report
        (and optionally the critic review) to the output directory
        specified in config.yaml.

        Saving is optional -- controlled by config['output']['save_reports'].
        If disabled, this node simply passes through without saving.

    HOW IT WORKS:
        1. Checks if save_reports is enabled in config
        2. Creates the output directory if it doesn't exist
        3. Generates a timestamped filename from the topic
        4. Writes the report (and optionally the review) to a .md file
        5. Returns a status update

    FILE NAMING:
        Reports are saved with timestamped names to avoid overwriting:
        Format: "reports/quantum_computing_20260218_221500.md"
        This ensures each research session creates a unique file.

    WHAT IT UPDATES IN STATE:
        - status: Final completion message with file path (if saved)

    Args:
        state (ResearchState): The current pipeline state.

    Returns:
        dict: State update with final 'status' message.
    """
    print("\n" + "="*60)
    print("SAVING REPORT")
    print("="*60)

    config = state["config"]
    output_config = config.get("output", {})

    # Check if saving is enabled in config
    if not output_config.get("save_reports", True):
        print("   INFO: Report saving is disabled in config.yaml")
        return {"status": "Pipeline complete! (Report saving disabled)"}

    try:
        # ----------------------------------------------------------------
        # Create the output directory if it doesn't exist
        # ----------------------------------------------------------------
        output_dir = output_config.get("output_dir", "reports/")
        os.makedirs(output_dir, exist_ok=True)

        # ----------------------------------------------------------------
        # Generate a clean, timestamped filename from the topic
        # Replace spaces and special chars with underscores
        # ----------------------------------------------------------------
        topic = state["topic"]
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")

        # Clean the topic for use as a filename
        clean_topic = "".join(
            c if c.isalnum() or c in (' ', '-') else '_'
            for c in topic
        ).replace(' ', '_').lower()[:50]  # Limit to 50 chars

        filename = f"{clean_topic}_{timestamp}.md"
        filepath = os.path.join(output_dir, filename)

        # ----------------------------------------------------------------
        # Build the complete file content
        # Combine the report with the critic review (if enabled)
        # ----------------------------------------------------------------
        report = state.get("report", "")
        review = state.get("review", {})
        include_review = output_config.get("include_review", True)

        file_content = report

        # Append the critic review if enabled and available
        if include_review and review:
            full_review = review.get("full_review", "")
            if full_review:
                file_content += "\n\n---\n\n" + full_review

        # ----------------------------------------------------------------
        # Write the file to disk
        # ----------------------------------------------------------------
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(file_content)

        print(f"   Report saved to: {filepath}")

        return {
            "status": f"Pipeline complete! Report saved to: {filepath}"
        }

    except Exception as e:
        print(f"   WARNING: Failed to save report: {e}")
        return {
            "status": f"Pipeline complete! (Save failed: {e})"
        }


# ============================================================
# GRAPH CONSTRUCTION
# ============================================================

def build_research_graph() -> StateGraph:
    """
    Build and compile the LangGraph research pipeline.

    WHY THIS FUNCTION EXISTS:
        This function constructs the LangGraph StateGraph that defines
        the entire research pipeline. It:
        1. Creates a new StateGraph with our ResearchState schema
        2. Adds all 5 agent nodes + the save node
        3. Connects them with edges (defines execution order)
        4. Compiles the graph (validates structure, prepares for execution)

    HOW LANGGRAPH WORKS:
        - StateGraph: The container for our pipeline
        - add_node(): Registers a function as a node in the graph
        - add_edge(): Connects two nodes (defines what runs after what)
        - START: Special LangGraph constant for the entry point
        - END: Special LangGraph constant for the exit point
        - compile(): Validates the graph and returns a runnable object

    GRAPH STRUCTURE:
        START -> planner -> search -> summarizer -> writer -> critic -> save -> END

        This is a LINEAR pipeline (no branching or loops in this version).
        Each node runs exactly once, in sequence.

    WHY LINEAR (not branching):
        For a portfolio project, a linear pipeline is clear and easy to
        understand. In production, you might add:
        - Conditional edges (re-run search if results are poor)
        - Loops (re-write report if critic score is too low)
        - Parallel execution (search multiple questions simultaneously)

    Returns:
        Compiled LangGraph StateGraph ready to be invoked.
        Call graph.invoke(initial_state) to run the pipeline.

    Example:
        >>> graph = build_research_graph()
        >>> result = graph.invoke({"topic": "Quantum Computing", "config": config})
    """

    # ----------------------------------------------------------------
    # Step 1: Create the StateGraph with our state schema
    # ResearchState defines what data the graph can store and pass around
    # ----------------------------------------------------------------
    graph = StateGraph(ResearchState)

    # ----------------------------------------------------------------
    # Step 2: Add all nodes to the graph
    # Each node is a function that takes state and returns state updates
    # The first argument is the node name (used in edges)
    # The second argument is the function to call
    # ----------------------------------------------------------------
    graph.add_node("planner", planner_node)         # Agent 1: Question decomposition
    graph.add_node("search", search_node)           # Agent 2: Web + Wikipedia search
    graph.add_node("summarizer", summarizer_node)   # Agent 3: Summarization
    graph.add_node("writer", writer_node)           # Agent 4: Report writing
    graph.add_node("critic", critic_node)           # Agent 5: Quality evaluation
    graph.add_node("save", save_node)               # Save report to disk

    # ----------------------------------------------------------------
    # Step 3: Connect nodes with edges (define execution order)
    # add_edge(from_node, to_node) means: after from_node completes,
    # run to_node next
    # ----------------------------------------------------------------
    graph.add_edge(START, "planner")        # Pipeline starts with Planner
    graph.add_edge("planner", "search")     # After Planner -> run Search
    graph.add_edge("search", "summarizer")  # After Search -> run Summarizer
    graph.add_edge("summarizer", "writer")  # After Summarizer -> run Writer
    graph.add_edge("writer", "critic")      # After Writer -> run Critic
    graph.add_edge("critic", "save")        # After Critic -> Save report
    graph.add_edge("save", END)             # After Save -> Pipeline ends

    # ----------------------------------------------------------------
    # Step 4: Compile the graph
    # compile() validates the graph structure (checks for disconnected nodes,
    # missing edges, etc.) and returns a runnable CompiledGraph object
    # ----------------------------------------------------------------
    compiled_graph = graph.compile()

    print("Research pipeline graph compiled successfully")
    print("   Flow: START -> Planner -> Search -> Summarizer -> Writer -> Critic -> Save -> END")

    return compiled_graph


def run_research_pipeline(topic: str, config: dict = None) -> Dict[str, Any]:
    """
    Run the complete multi-agent research pipeline for a given topic.

    WHY THIS FUNCTION EXISTS:
        This is the main entry point for the research pipeline. It:
        1. Loads configuration (if not provided)
        2. Builds the LangGraph pipeline
        3. Creates the initial state
        4. Runs the pipeline
        5. Returns the final state with all results

        This function is called by app.py (Streamlit UI) to run the
        entire research process from start to finish.

    HOW IT WORKS:
        1. Load config from config.yaml
        2. Build the compiled LangGraph graph
        3. Create the initial state with the topic and config
        4. Call graph.invoke() to run all 5 agents in sequence
        5. Return the final state (contains report, review, etc.)

    INITIAL STATE:
        The initial state must have all required TypedDict fields.
        Fields that will be populated by agents start as empty values:
        - sub_questions: [] (filled by Planner)
        - search_results: {} (filled by Search)
        - summaries: {} (filled by Summarizer)
        - report: "" (filled by Writer)
        - review: {} (filled by Critic)

    Args:
        topic (str): The research topic to investigate.
                     Example: "Impact of AI on Healthcare"
        config (dict, optional): Configuration dictionary. If None,
                                  loads from config.yaml automatically.

    Returns:
        Dict[str, Any]: The final pipeline state containing:
                        - topic: The original topic
                        - sub_questions: Generated sub-questions
                        - search_results: Raw search data
                        - summaries: Per-topic summaries
                        - report: Full Markdown research report
                        - review: Critic's quality evaluation
                        - status: Final status message
                        - error: Any error that occurred (or None)

    Raises:
        Does NOT raise exceptions -- errors are captured in state['error'].
        This ensures the UI always gets a response, even on failure.

    Example:
        >>> result = run_research_pipeline("Quantum Computing")
        >>> print(result['report'][:500])
        >>> print(f"Score: {result['review']['score']}/10")
    """

    # ----------------------------------------------------------------
    # Step 1: Load configuration
    # ----------------------------------------------------------------
    if config is None:
        config = load_config()

    print("\n" + "="*60)
    print("STARTING MULTI-AGENT RESEARCH PIPELINE")
    print(f"Topic: {topic}")
    print("="*60)

    # ----------------------------------------------------------------
    # Step 2: Build the compiled LangGraph pipeline
    # ----------------------------------------------------------------
    graph = build_research_graph()

    # ----------------------------------------------------------------
    # Step 3: Create the initial state
    # All agent-populated fields start empty; they'll be filled as
    # each agent runs and updates the state
    # ----------------------------------------------------------------
    initial_state: ResearchState = {
        "topic": topic,                 # The research topic (never changes)
        "config": config,               # Shared config for all agents
        "sub_questions": [],            # Will be filled by Planner Agent
        "search_results": {},           # Will be filled by Search Agent
        "summaries": {},                # Will be filled by Summarizer Agent
        "report": "",                   # Will be filled by Writer Agent
        "review": {},                   # Will be filled by Critic Agent
        "error": None,                  # None = no error (yet)
        "status": "Pipeline starting..."
    }

    # ----------------------------------------------------------------
    # Step 4: Run the pipeline
    # graph.invoke() executes all nodes in sequence, passing state
    # between them. It returns the final state after all nodes complete.
    # ----------------------------------------------------------------
    try:
        final_state = graph.invoke(initial_state)

        print("\n" + "="*60)
        print("PIPELINE COMPLETED SUCCESSFULLY")
        print(f"Topic: {topic}")
        print(f"Report: {len(final_state.get('report', '').split())} words")
        print(f"Score: {final_state.get('review', {}).get('score', 'N/A')}/10")
        print("="*60)

        return final_state

    except Exception as e:
        # ----------------------------------------------------------------
        # If the entire pipeline fails (very rare -- individual agents
        # have their own error handling), capture the error here
        # ----------------------------------------------------------------
        print(f"\nERROR: Pipeline failed with unexpected error: {e}")
        return {
            "topic": topic,
            "config": config,
            "sub_questions": [],
            "search_results": {},
            "summaries": {},
            "report": f"# Pipeline Failed\n\nAn unexpected error occurred: {str(e)}",
            "review": {"score": 0, "grade": "F", "verdict": "PIPELINE FAILED"},
            "error": str(e),
            "status": f"Pipeline failed: {str(e)}"
        }
