# ============================================================
# agents/search_agent.py
# ============================================================
# PURPOSE:
#   This module implements the Search Agent -- the SECOND agent
#   in the multi-agent research pipeline. It takes the list of
#   sub-questions generated by the Planner Agent and fetches
#   real-world information for each one using two free tools:
#   DuckDuckGo (web search) and Wikipedia (encyclopedic search).
#
# WHY WE NEED A SEARCH AGENT:
#   LLMs have a knowledge cutoff date -- they don't know about
#   recent events or the latest research. The Search Agent
#   "grounds" the pipeline in real, current information by
#   fetching live data from the web. This is the core principle
#   behind Retrieval-Augmented Generation (RAG): retrieve first,
#   then generate. Without this agent, the report would be based
#   solely on the LLM's training data, which may be outdated.
#
# HOW IT FITS IN THE PIPELINE:
#   Planner Agent -> [SEARCH AGENT] -> Raw Results -> Summarizer Agent
#
# DUAL-SOURCE STRATEGY:
#   We use TWO search sources intentionally:
#   1. DuckDuckGo: Current web pages, news, blogs, recent articles
#      -> Gives us recency and breadth
#   2. Wikipedia: Authoritative, structured encyclopedic content
#      -> Gives us depth and factual accuracy
#   Together they provide both current AND authoritative information.
#
# TECHNOLOGY USED:
#   - tools/web_search.py: DuckDuckGo search wrapper (free, no API key)
#   - tools/wikipedia_tool.py: Wikipedia search wrapper (free, no API key)
#   - config_loader: Reads settings from config.yaml
#
# EXAMPLE:
#   Input:  ["What is quantum computing?", "What are quantum computing applications?"]
#   Output: {
#     "What is quantum computing?": {
#       "web_results": [...],
#       "wikipedia": {...},
#       "formatted_context": "..."
#     },
#     ...
#   }
# ============================================================

from tools.web_search import search_web, format_search_results          # DuckDuckGo search
from tools.wikipedia_tool import search_wikipedia, format_wikipedia_result  # Wikipedia search
from utils.config_loader import load_config                              # Config loader
from typing import List, Dict, Any                                       # Type hints


def run_search_agent(sub_questions: List[str], config: dict = None) -> Dict[str, Any]:
    """
    Run the Search Agent to fetch web and Wikipedia results for each sub-question.

    WHY THIS FUNCTION EXISTS:
        This is the core function of the Search Agent. For each sub-question
        generated by the Planner Agent, it fetches relevant information from
        two sources: DuckDuckGo (current web) and Wikipedia (authoritative facts).

        This dual-source approach is critical because:
        - DuckDuckGo gives us the LATEST information (news, recent research)
        - Wikipedia gives us RELIABLE background knowledge (definitions, history)
        Together they give the Summarizer Agent rich, well-rounded context.

    HOW IT WORKS:
        1. Load configuration (if not provided)
        2. For each sub-question:
           a. Search DuckDuckGo for web results
           b. Search Wikipedia for encyclopedic content (if enabled in config)
           c. Combine and format all results into a single context string
           d. Store results in a structured dictionary
        3. Return the complete results dictionary

    RESULT STRUCTURE:
        The function returns a dictionary where:
        - Keys are the sub-question strings
        - Values are dictionaries containing:
          - 'question': The sub-question itself
          - 'web_results': List of DuckDuckGo result dicts
          - 'wikipedia': Wikipedia result dict (or None if disabled)
          - 'formatted_context': All results combined as a single text string
            (this is what the Summarizer Agent reads)

    Args:
        sub_questions (List[str]): List of sub-questions from the Planner Agent.
                                    Example: ["What is AI?", "How does AI work?"]
        config (dict, optional): Configuration dictionary. If None, loads
                                  from config.yaml automatically.

    Returns:
        Dict[str, Any]: A dictionary mapping each sub-question to its search results.
                        Structure:
                        {
                          "What is AI?": {
                            "question": "What is AI?",
                            "web_results": [{"title": ..., "url": ..., "snippet": ...}, ...],
                            "wikipedia": {"title": ..., "summary": ..., "url": ...},
                            "formatted_context": "Result 1:\nTitle: ...\n..."
                          },
                          ...
                        }
                        Returns empty dict if sub_questions is empty.

    Example:
        >>> questions = ["What is machine learning?", "What are ML applications?"]
        >>> results = run_search_agent(questions)
        >>> print(results["What is machine learning?"]["formatted_context"][:100])
    """

    # ----------------------------------------------------------------
    # Step 1: Load configuration if not provided
    # ----------------------------------------------------------------
    if config is None:
        config = load_config()

    # ----------------------------------------------------------------
    # Step 2: Extract search settings from config
    # These control how many results to fetch and whether to use Wikipedia
    # ----------------------------------------------------------------
    max_results = config.get("search", {}).get("max_results", 3)
    wikipedia_sentences = config.get("search", {}).get("wikipedia_sentences", 5)
    request_timeout = config.get("search", {}).get("request_timeout", 10)
    use_wikipedia = config.get("agents", {}).get("search", {}).get("use_wikipedia", True)

    # ----------------------------------------------------------------
    # Step 3: Initialize the results dictionary
    # This will hold all search results, keyed by sub-question
    # ----------------------------------------------------------------
    all_results = {}

    print(f"\nSearch Agent starting -- {len(sub_questions)} sub-questions to research...")

    # ----------------------------------------------------------------
    # Step 4: Process each sub-question one by one
    # ----------------------------------------------------------------
    for i, question in enumerate(sub_questions, start=1):
        print(f"\n   [{i}/{len(sub_questions)}] Searching: '{question[:60]}...'" if len(question) > 60
              else f"\n   [{i}/{len(sub_questions)}] Searching: '{question}'")

        # Initialize the result structure for this question
        question_results = {
            "question": question,           # Store the question itself for reference
            "web_results": [],              # Will hold DuckDuckGo results
            "wikipedia": None,             # Will hold Wikipedia result (or None)
            "formatted_context": ""        # Will hold combined text for the LLM
        }

        # ----------------------------------------------------------------
        # Step 4a: Perform DuckDuckGo web search
        # This gives us current, real-world web pages about the topic
        # ----------------------------------------------------------------
        print(f"      Searching DuckDuckGo...")
        web_results = search_web(
            query=question,
            max_results=max_results,
            timeout=request_timeout
        )
        question_results["web_results"] = web_results
        print(f"      Got {len(web_results)} web results")

        # ----------------------------------------------------------------
        # Step 4b: Perform Wikipedia search (if enabled in config)
        # This gives us authoritative, encyclopedic background information
        # ----------------------------------------------------------------
        wikipedia_result = None
        if use_wikipedia:
            print(f"      Searching Wikipedia...")
            # Extract the key topic from the question for Wikipedia search
            # Wikipedia works better with topic names than full questions
            wiki_query = extract_wiki_query(question)
            wikipedia_result = search_wikipedia(
                query=wiki_query,
                sentences=wikipedia_sentences
            )
            question_results["wikipedia"] = wikipedia_result

            # Check if Wikipedia actually found something useful
            if wikipedia_result.get("title") != "Not Found":
                print(f"      Wikipedia: '{wikipedia_result.get('title', 'N/A')}'")
            else:
                print(f"      Wikipedia: No article found")

        # ----------------------------------------------------------------
        # Step 4c: Combine all results into a single formatted context string
        # This is the text that will be passed to the Summarizer Agent.
        # Having everything in one string makes it easy for the LLM to read.
        # ----------------------------------------------------------------
        question_results["formatted_context"] = build_context_string(
            question=question,
            web_results=web_results,
            wikipedia_result=wikipedia_result
        )

        # Store this question's results in the main dictionary
        all_results[question] = question_results

    print(f"\nSearch Agent completed -- gathered data for {len(all_results)} sub-questions")
    return all_results


def extract_wiki_query(question: str) -> str:
    """
    Extract a concise Wikipedia-friendly search query from a full question.

    WHY THIS FUNCTION EXISTS:
        Wikipedia's search works best with topic names or short phrases,
        not full question sentences. For example:
        - Bad:  "What are the applications of quantum computing in cryptography?"
        - Good: "quantum computing cryptography"

        This function strips question words and extracts the core topic,
        improving Wikipedia search accuracy significantly.

    HOW IT WORKS:
        1. Removes common question-starting words (What, How, Why, etc.)
        2. Removes filler words (are, is, the, of, etc.)
        3. Returns the remaining key terms as the search query
        4. Falls back to the original question if nothing useful remains

    Args:
        question (str): A full research sub-question.
                        Example: "What are the main applications of blockchain?"

    Returns:
        str: A concise search query suitable for Wikipedia.
             Example: "blockchain applications"

    Example:
        >>> extract_wiki_query("What is quantum computing and how does it work?")
        "quantum computing"
    """
    # Words to remove from the beginning of questions
    question_starters = [
        "what is", "what are", "what were", "what will",
        "how does", "how do", "how is", "how are",
        "why is", "why are", "why does",
        "when did", "when was", "when will",
        "who are", "who is", "who were",
        "where is", "where are",
        "which are", "which is"
    ]

    # Convert to lowercase for matching
    query = question.lower().strip()

    # Remove question starters
    for starter in question_starters:
        if query.startswith(starter):
            query = query[len(starter):].strip()
            break

    # Remove trailing question mark
    query = query.rstrip("?").strip()

    # Remove common filler words that don't help Wikipedia search
    filler_words = ["the", "a", "an", "and", "or", "in", "of", "for", "to", "its"]
    words = query.split()
    # Only remove filler words if we have enough words remaining
    if len(words) > 3:
        words = [w for w in words if w not in filler_words]
    query = " ".join(words)

    # If we stripped too much, fall back to the original question
    if len(query) < 3:
        return question

    return query


def build_context_string(
    question: str,
    web_results: list,
    wikipedia_result: dict
) -> str:
    """
    Combine web search results and Wikipedia content into a single context string.

    WHY THIS FUNCTION EXISTS:
        The Summarizer Agent needs all the research data for a sub-question
        in a single, readable text format. This function combines DuckDuckGo
        results and Wikipedia content into one well-structured string that
        the LLM can easily read and summarize.

        Having a single context string (rather than separate data structures)
        makes the Summarizer Agent's prompt simpler and more effective.

    HOW IT WORKS:
        1. Starts with a header showing the question being researched
        2. Adds formatted DuckDuckGo web results (if any)
        3. Adds formatted Wikipedia content (if available and not an error)
        4. Returns the complete combined string

    Args:
        question (str): The sub-question being researched.
        web_results (list): List of DuckDuckGo result dictionaries.
        wikipedia_result (dict): Wikipedia result dictionary (or None).

    Returns:
        str: A formatted string combining all search results.
             Returns a "no results" message if both sources returned nothing.

    Example:
        >>> context = build_context_string("What is AI?", web_results, wiki_result)
        >>> print(context[:200])
        "RESEARCH QUESTION: What is AI?
        ===
        WEB SEARCH RESULTS:
        Result 1:
        Title: Artificial Intelligence - Overview
        ..."
    """
    parts = []

    # Add a clear header showing which question this context is for
    parts.append(f"RESEARCH QUESTION: {question}")
    parts.append("=" * 60)

    # ----------------------------------------------------------------
    # Add DuckDuckGo web search results
    # format_search_results() converts the list of dicts to readable text
    # ----------------------------------------------------------------
    if web_results:
        parts.append("\nWEB SEARCH RESULTS (DuckDuckGo):")
        parts.append(format_search_results(web_results))
    else:
        parts.append("\nWEB SEARCH RESULTS: No web results found.")

    # ----------------------------------------------------------------
    # Add Wikipedia content (if available and not an error result)
    # We check for "Not Found" title to skip failed Wikipedia searches
    # ----------------------------------------------------------------
    if wikipedia_result and wikipedia_result.get("title") != "Not Found":
        parts.append("\n\nWIKIPEDIA REFERENCE:")
        parts.append(format_wikipedia_result(wikipedia_result))

    # Join all parts into a single string
    context = "\n".join(parts)

    # If we got absolutely nothing, return a clear message
    if not web_results and (not wikipedia_result or wikipedia_result.get("title") == "Not Found"):
        return f"RESEARCH QUESTION: {question}\n\nNo search results found for this question."

    return context


def get_search_summary(all_results: Dict[str, Any]) -> str:
    """
    Generate a brief summary of what the Search Agent found.

    WHY THIS FUNCTION EXISTS:
        After the Search Agent runs, it's useful to have a quick overview
        of what was found -- how many web results, which Wikipedia articles
        were found, etc. This summary is used for logging and for displaying
        progress in the Streamlit UI.

    Args:
        all_results (Dict[str, Any]): The complete results dictionary from
                                       run_search_agent().

    Returns:
        str: A human-readable summary of the search results.

    Example:
        >>> summary = get_search_summary(results)
        >>> print(summary)
        "Search Summary: 5 questions researched, 15 web results, 4 Wikipedia articles"
    """
    total_web = sum(len(r.get("web_results", [])) for r in all_results.values())
    total_wiki = sum(
        1 for r in all_results.values()
        if r.get("wikipedia") and r["wikipedia"].get("title") != "Not Found"
    )

    return (
        f"Search Summary: {len(all_results)} questions researched | "
        f"{total_web} web results | "
        f"{total_wiki} Wikipedia articles found"
    )
