# ============================================================
# tools/web_search.py
# ============================================================
# PURPOSE:
#   This module provides the web search capability used by the
#   Search Agent. It wraps the DuckDuckGo search library into
#   a clean, reusable function that returns structured results.
#
# WHY DUCKDUCKGO:
#   - Completely FREE — no API key required
#   - No rate limiting for reasonable usage
#   - Returns clean, relevant results
#   - Privacy-focused (no tracking)
#   - The 'duckduckgo-search' Python library makes it easy to use
#
# WHY WE NEED THIS:
#   Agents need real-world, up-to-date information to produce
#   accurate research reports. Without web search, the LLM can
#   only rely on its training data (which has a knowledge cutoff).
#   Web search grounds the agent in current, factual information.
#
# USAGE:
#   from tools.web_search import search_web
#   results = search_web("quantum computing applications 2024", max_results=3)
# ============================================================

from duckduckgo_search import DDGS   # DuckDuckGo search library (no API key needed)
from typing import List, Dict        # Type hints for better code clarity


def search_web(query: str, max_results: int = 3, timeout: int = 10) -> List[Dict[str, str]]:
    """
    Search the web using DuckDuckGo and return structured results.

    WHY THIS FUNCTION EXISTS:
        The Search Agent needs to fetch real-world information for each
        sub-question generated by the Planner Agent. This function
        provides a clean interface to DuckDuckGo search, returning
        results in a consistent format that the Summarizer Agent can
        easily process.

    HOW IT WORKS:
        1. Takes a search query string
        2. Uses the DDGS (DuckDuckGo Search) library to fetch results
        3. Extracts title, URL, and snippet from each result
        4. Returns a list of dictionaries with structured data
        5. Handles errors gracefully (returns empty list on failure)

    Args:
        query (str): The search query to look up.
                     Example: "quantum computing applications 2024"
        max_results (int): Maximum number of results to return.
                           More results = more comprehensive but slower.
                           Default: 3 (from config.yaml)
        timeout (int): Request timeout in seconds.
                       Prevents hanging if DuckDuckGo is slow.
                       Default: 10 seconds

    Returns:
        List[Dict[str, str]]: A list of search result dictionaries.
                              Each dictionary contains:
                              - 'title': The webpage title
                              - 'url': The webpage URL
                              - 'snippet': A brief text excerpt from the page
                              - 'source': Always 'duckduckgo' (for tracking)

                              Example return value:
                              [
                                {
                                  'title': 'Quantum Computing Explained',
                                  'url': 'https://example.com/quantum',
                                  'snippet': 'Quantum computers use qubits...',
                                  'source': 'duckduckgo'
                                },
                                ...
                              ]

                              Returns empty list [] if search fails.

    Example:
        >>> results = search_web("AI in healthcare 2024", max_results=3)
        >>> for r in results:
        ...     print(r['title'], r['url'])
    """

    # Initialize an empty list to store our search results
    results = []

    try:
        # ----------------------------------------------------------------
        # Create a DDGS (DuckDuckGo Search) instance and perform the search
        # DDGS() is a context manager that handles the HTTP session
        # ddgs.text() performs a text search (as opposed to image/news search)
        # ----------------------------------------------------------------
        with DDGS() as ddgs:
            # Fetch search results from DuckDuckGo
            # region='wt-wt' means worldwide results (not region-specific)
            # safesearch='off' allows all results (not filtered)
            raw_results = list(ddgs.text(
                query,
                max_results=max_results,
                region='wt-wt',
                safesearch='off'
            ))

        # ----------------------------------------------------------------
        # Process each raw result into our standardized format
        # DuckDuckGo returns: {'title': ..., 'href': ..., 'body': ...}
        # We rename 'href' to 'url' and 'body' to 'snippet' for clarity
        # ----------------------------------------------------------------
        for item in raw_results:
            results.append({
                'title': item.get('title', 'No title'),       # Page title
                'url': item.get('href', 'No URL'),             # Page URL
                'snippet': item.get('body', 'No description'), # Text excerpt
                'source': 'duckduckgo'                         # Track the source
            })

    except Exception as e:
        # ----------------------------------------------------------------
        # If search fails for any reason (network error, rate limit, etc.)
        # we return an empty list rather than crashing the entire pipeline.
        # The Search Agent will handle empty results gracefully.
        # ----------------------------------------------------------------
        print(f"WARNING: Web search failed for query '{query}': {e}")
        return []

    return results


def format_search_results(results: List[Dict[str, str]]) -> str:
    """
    Format a list of search results into a readable text string.

    WHY THIS FUNCTION EXISTS:
        The LLM (Summarizer Agent) needs to read the search results as
        plain text, not as a Python list of dictionaries. This function
        converts the structured results into a clean, readable format
        that the LLM can easily understand and summarize.

    HOW IT WORKS:
        Takes the list of result dictionaries and formats each one
        with its number, title, URL, and snippet on separate lines.
        This makes it easy for the LLM to identify individual sources.

    Args:
        results (List[Dict[str, str]]): List of search result dictionaries
                                        as returned by search_web().

    Returns:
        str: A formatted string with all results, ready to be passed
             to the LLM as context.
             Returns "No search results found." if the list is empty.

    Example:
        >>> results = [{'title': 'Quantum Computing', 'url': 'http://...', 'snippet': '...'}]
        >>> print(format_search_results(results))
        Result 1:
        Title: Quantum Computing
        URL: http://...
        Content: ...
        ---
    """

    # Handle the case where no results were found
    if not results:
        return "No search results found."

    # Build the formatted string by iterating through results
    formatted_parts = []

    for i, result in enumerate(results, start=1):
        # Format each result with clear labels for the LLM to parse
        formatted_parts.append(
            f"Result {i}:\n"
            f"Title: {result.get('title', 'N/A')}\n"
            f"URL: {result.get('url', 'N/A')}\n"
            f"Content: {result.get('snippet', 'N/A')}\n"
            f"---"
        )

    # Join all formatted results with newlines between them
    return "\n".join(formatted_parts)
